name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Checkout wlvncc Code
      uses: actions/checkout@v4
      with:
        repository: any1/wlvncc
        path: BUILD
        
    - name: Checkout aml Code
      uses: actions/checkout@v4
      with:
        repository: any1/aml
        path: BUILD/subprojects/aml

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build RPM
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace fedora:latest bash -c "
          dnf install -y dnf-plugins-core rpmdevtools &&
          spectool --get-files --all SPECS/*.spec &&
          dnf builddep -y SPECS/*.spec &&
          rpmbuild --define '_topdir /workspace' -ba SPECS/*.spec
        "

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: RPMS/
